declare module "@env" {
  export const API_KEY: string;
  export const AUTH_DOMAIN: string;
  export const FIREBASE_PROJECT_ID: string;
  export const STORAGE_BUCKET: string;
  export const MESSAGING_SENDER_ID: string;
  export const APP_ID: string;
  export const GOOGLE_CLIENT_ID: string;
  export const SENTRY_DSN: string;
  export const EXPO_TUNNEL_SUBDOMAIN: string;
  export const PROJECT_ID: string;
  export const DATABASE_URL: string;
  export const CLOUDINARY_CLOUD_NAME: string;
  export const CLOUDINARY_UPLOAD_PRESET: string;
  export const PARSE_SERVER_URL: string;
  export const PARSE_APP_ID: string;
  export const PARSE_MASTER_KEY: string;
  export const APP_IDENTIFIER: string;
}
