apiVersion: v1
kind: Service
metadata:
  name: parse-server
  namespace: parse-server
spec:
  type: NodePort
  ports:
  - port: 1337
    targetPort: 1337
    nodePort: 30001
  selector:
    app: parse-server