apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  namespace: parse-server
type: Opaque
stringData:
  firebase-secret.json: |
    {
      "type": "your_type",
      "project_id": "your_project_id",
      "private_key_id": "your_private_key_id",
      "private_key": "-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n",
      "serviceAccount": "./firebase-secret.json"
    } 
